#!/usr/bin/env bash

function get_pid() {
	grep -x google-chrome <<<${WINDOW_CLASSES} > /dev/null && {
		PID=$(
			ps u -C chrome |
			grep "\-\-service-sandbox-type=audio" |
			column -t -o " " |
			cut -d " " -f2
		)

		return
	}

	PID=$(
		egrep "^_NET_WM_PID" <<<${WINDOW} |
		cut -d " " -f3
	)
}

function move_sink_input() {
	INPUT_ID=$(cut -d "-" -f1 <<<${INPUT})
	SINK_ID=$(cut -d "-" -f2 <<<${INPUT})

	[[ "$SINK_ID" -lt "$(tail -n1 <<<${SINK_IDS})" ]] && {
		NEW_SINK_ID=$(grep -A1 ${SINK_ID} <<<${SINK_IDS} | tail -n1)
	} || {
		NEW_SINK_ID=$(head -n1 <<<${SINK_IDS})
	}

	pacmd move-sink-input ${INPUT_ID} ${NEW_SINK_ID}

	echo New sink: $(egrep "^${NEW_SINK_ID}\b" <<<${SINKS})
}

PID=0
NEW_SINK_ID=0

SINKS=$(pactl list short sinks)
SINK_IDS=$(cut -f1 <<<${SINKS})

WINDOW=$(xprop)
WINDOW_CLASSES=$(grep WM_CLASS <<<${WINDOW} | sed -e 's/.*=\(.*\)$/\1/' -e 's/[",]//g' | xargs -n1)

get_pid

echo Window: ${WINDOW_CLASSES}
echo PID: ${PID}

INPUTS=$(
	pacmd list-sink-inputs |
		sed 's/\\"//g' |
		xargs |
		sed 's/index: /\n/g' |
		grep "application.process.id = $PID" |
		sed 's/^\([0-9]*\).*sink: \([0-9]*\).*/\1-\2/'
)

[[ -z ${INPUTS} ]] && {
	echo "No audio input in window."
	exit
}

for INPUT in ${INPUTS}
	do move_sink_input
done
