#!/bin/bash

INPUT=$(
	pacmd list-sink-inputs | 
		xargs | 
		sed 's/index: /\n/g' | 
		grep "application.process.id = $(
			xprop | 
			egrep "^_NET_WM_PID" | 
			cut -d " " -f3
		)" | 
		sed 's/^\([0-9]*\).*sink: \([0-9]*\).*/\1 \2/'
)

INPUT_ID=$(cut -d " " -f1 <<<$INPUT)
SINK_ID=$(cut -d " " -f2 <<<$INPUT)

NEW_SINK_ID=$[SINK_ID+1]

[ "$NEW_SINK_ID" -gt "$(pactl list short sinks | tail -n1 | cut -f1)" ] && NEW_SINK_ID=0

pacmd move-sink-input $INPUT_ID $NEW_SINK_ID
